---
- hosts: testing
  
  tasks:
  
   - name: Adicionar estrutura de diretorios
     file:
       dest: "{{ diretorios }}"
       state: directory
       recurse: yes
       owner: root
       group: root      
       mode: 755
        