---
# tasks file for postfix

- name: Instala servidor de Email
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items:
    - postifix
    - courier-pop
    - courier-imap
  register: postifix_packages_installed
  notify:
    - Start Postifix
