---

- name: Define o arquivo de configurção do servidor DNS
  when: bind9_installed|success
  copy:
    src: "{{item}}"
    dest: /etc/bind/
    owner: root
    group: root
    mode: 0644
  with_items:
    - files/named.conf.local
    - files/named.conf.options
  notify:
    - Reload Bind9

- name: Define o arquivo de registro de Zona
  when: bind9_installed|success
  copy:
    src: "{{item}}"
    dest: /var/cache/bind/
    owner: root
    group: root
    mode: 0644
  with_items:
    - files/db.dexter.interna
    - files/rev.dexter.interna
  notify:
    - Reload Bind9
