---
- hosts: testing
  
  tasks:
  
   - name: Instala pacote NTP
     apt:
       name: ntp
       state: installed
       update_cache: true
     register: ntp_instaled
     
   - name: Define o arquivo de  configuracao do servidor NTP
     when: ntp_instaled|success
     copy:
       src: /home/ansible/aula02/ntp.conf
       dest: /etc/ntp.conf
       owner: root
       group: root
       mode: 0644
          
       
        