---
- hosts: testing
  become: true

  tasks:

  # - name: Instalar pacote rsync para sevidor de Teste
  #   apt:
  #     name: rsync
  #     state: installed
  #     update_cache: true

   - name: Synchronization of src on the control machine to dest on the remote hosts
     synchronize:
       src: /nas/lib
       dest: /var/weblogic/lib
       set_remote_user: ansbile
     delegate_to: testing
