---
- hosts: testing
  become: true

  tasks:

   - name: Synchronization of src on the control machine to dest on the remote hosts
     synchronize:
       src: /nas/lib
       dest: /var/weblogic/lib
       delegate_to: "{{ inventory_hostname }}"
