---
- name: Define o arquivo de configurção do servidor Rsyslog
  when: rsyslog_installed|success
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Rsyslog
